name: Events Demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'
      - 'feat/**'
      - 'updated-*'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event info
        run: echo "${{ toJSON(github.event) }}"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Build Project
        run: npm run build
      - name: Deploy to host
        run: echo "Deploying to cloud host..."